### ISSUE TITLE
"Comments" section do not support carriage return 

### ISSUE THREAD

**Issue by bdsbds** [jfyuen/timesheets#26]
Adding _carriage return_ in "Commentaires" section leads to strange behavior in TASKS table : 

https://we.tl/t-HZNsO9vcQx   (screenshot)

这不是一个大问题。
非常感谢 ！

**Comment by bdsbds** [comment]
Merci beaucoup ! Comme l'apparence était très bizarre au résultat du select, je pensais qu'il s'agissait d'un bug. Ouf !PS: bizarre d'avoir l'idée de mettre des retours à la ligne dans les commentaires :-)envoyé : 23 juin 2022 à 14:34de : Jean-François YUEN ***@***.***>à : jfyuen/timesheets ***@***.***>cc : bdsbds ***@***.***>, Author ***@***.***>objet : Re: [jfyuen/timesheets] "Comments" section do not support carriage return (Issue #26) I don't think there's a bug, it is just the way sqlite displays new lines. You can also have a look with a csv export:$ sqlite3 timesheets.db
sqlite> .mode csv
sqlite> .headers on
sqlite> select * from TASKS;
USER_ID,TIME_ALLOCATION_ID,ACTIVITY_ID,DAY,COMMENT
8,0,2,2022-06-23,"a
b
c"
The string a\nb\nc is correctly displayed for the COMMENT column.Is there any side effect on the application side?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jfyuen** [comment]
Closing issue as non-bug :)
